---
    - name: HAProxy
      yum: 
       name: haproxy
       state: present

    - name: HAProxy config
      template:
       src: etc/haproxy/{{ ansible_hostname }}.cfg
       dest: /etc/haproxy/haproxy.cfg
       owner: root
       group: root
       mode: 0644

    - name: haproxy restart
      systemd:
        name: haproxy
        state: restarted


    - name: Configure firewall
      firewalld:
       port: 80/tcp
       permanent: yes
       state: enabled
       immediate: yes

    
