---
  
    - name: Install epel
      yum: 
       name:
        - epel-release
        - nano
        - ntp
       update_cache: yes
       state: present

    - name: Enable and start firewalld
      systemd:
       name: firewalld
       enabled: yes
       state: started

    - name: Set timezone
      timezone:
        name: Europe/Moscow

    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1

    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1

    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        reload: yes
    - name: Enable and start ntpd
      systemd:
        name: ntpd
        enabled: yes
        state: started

    - name: Configure firewall Rsyslog
      firewalld:
        port: 514/tcp
        permanent: yes
        state: enabled
        immediate: yes
